name: DeployToGitHubPages
   
# Controls when the action will run
on:
  push:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools

    - name: Publish .NET Core Project
      run: dotnet publish src/RandomWorkings.BlazorBattleships.csproj -c:Release -p:GHPages=true -o build --nologo

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # upload entire directory
        path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    runs-on: ubuntu-latest    

    needs: build

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2