name: DeployToGitHubPages
   
# Controls when the action will run
on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - name: Publish app
      run: dotnet publish src/RandomWorkings.BlazorBattleships.csproj -c Release -o release --nologo

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.4
      with:
        FOLDER: release/src/wwwroot
